### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamnaz** [icuntcode/ChainWallet-breaker#1]
('module name:', '__main__')
('parent process:', 4523)
('process id:', 7149)
('Generating ', 15626, 'rounds of sha256 for all ', 6, ' lowercase letter passwords')
(4827117915776, ' possibilities. This will take a while...')
('Current password: ', 'aaaaaa')
Traceback (most recent call last):
  File "puzz.py", line 119, in <module>
    public_key = private_key_to_public_key(private_key)
  File "puzz.py", line 40, in private_key_to_public_key
    pk = PrivateKey().fromString(bytes.fromhex(private_key))
AttributeError: type object 'str' has no attribute 'fromhex'

**Comment by icuntcode** [comment]
Are you running this on Python 3.6 or higher, and did you install starkbank-ecdsa==0.1.4?

**Comment by hamnaz** [comment]
yes starkbank installed, and python 3.7
return above error

**Comment by hamnaz** [comment]
Requirement already satisfied: starkbank-ecdsa in /usr/local/lib/python2.7/dist-packages (0.1.5)

**Comment by icuntcode** [comment]
>starkbank-ecdsa in /usr/local/lib/python2.7/dist-packages (0.1.5)

You are checking the Python 2.7 path there. Do you have both versions installed (2.7/3.x)?
In that case, make sure you are running the application from your python 3.6 path, not the 2.7 one.

To make sure you are in the right version type: 
`python -V`
