### ISSUE TITLE
error starkbank-ecdsa 0.1.5 installed, check maybe you have 0.1.4 

### ISSUE THREAD

**Issue by hamnaz** [icuntcode/ChainWallet-breaker#2]
Select a mode - Random (r/R) or Exhaustive (e/E): r
Running: __main__
parent process: 6
process id: 50
Insert a first password to be tested (if you feel lucky): youyou
Running in random mode
Using input password:  youyou
Current password:  youyou
SHA256 times:  4
Traceback (most recent call last):
  File "main.py", line 137, in<module>
    public_key = private_key_to_public_key(private_key)
  File "main.py", line 43, in private_key_to_public_key
    return '04' + pk.publicKey().toString().hex().upper()
AttributeError: 'str' object has no attribute 'hex'

chawla@i3-6100:~$ python --version
Python 2.7.15+
chawla@i3-6100:~$ python3 --version
Python 3.7.3
chawla@i3-6100:~$ pip --version
pip 19.2.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
chawla@i3-6100:~$ pip3 --version
pip 19.2.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
chawla@i3-6100:~$ pip2.7 --version
pip 19.2.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
chawla@i3-6100:~$ pip2 --version
pip 19.2.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

**Comment by hamnaz** [comment]
ok found solution uninstall starkbank ecdsa 0.015
install starkbank ecdsa 0.014
all working

**Comment by icuntcode** [comment]
Hi, your error is related to the python version only, not the starkbank version, as shown in a similar issues here:

https://github.com/Isaacdelly/Plutus/issues/98
https://github.com/vkobel/ethereum-generate-wallet/issues/10

I will add the requirements to the code directly.
